"""modify

Revision ID: 134a7f3cb501
Revises: fdfd1ddd8b20
Create Date: 2017-05-16 09:53:33.034273

"""

# revision identifiers, used by Alembic.
revision = '134a7f3cb501'
down_revision = 'fdfd1ddd8b20'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushtexts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('pushtexts', sa.Column('content', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'pushtexts', 'users', ['author_id'], ['id'])
    op.drop_column('pushtexts', 'textarea')
    op.drop_column('pushtexts', 'is_to_all')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushtexts', sa.Column('is_to_all', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('pushtexts', sa.Column('textarea', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'pushtexts', type_='foreignkey')
    op.drop_column('pushtexts', 'content')
    op.drop_column('pushtexts', 'author_id')
    ### end Alembic commands ###
