"""init

Revision ID: 7f0c7f9f6c68
Revises: None
Create Date: 2017-05-21 12:54:53.053877

"""

# revision identifiers, used by Alembic.
revision = '7f0c7f9f6c68'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('openid', sa.String(length=32), nullable=False),
    sa.Column('studentid', sa.String(length=20), nullable=True),
    sa.Column('studentpwd', sa.String(length=70), nullable=True),
    sa.Column('libraryid', sa.String(length=20), nullable=True),
    sa.Column('librarypwd', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('openid'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wechatusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('realname', sa.String(length=32), nullable=True),
    sa.Column('classname', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('headimgurl', sa.String(length=150), nullable=True),
    sa.Column('regtime', sa.DateTime(), nullable=False),
    sa.Column('user_setting', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('registrations',
    sa.Column('user_openid', sa.Integer(), nullable=True),
    sa.Column('user_groupid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_groupid'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_openid'], ['wechatusers.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('passwd_hash', sa.String(length=128), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_register_time'), 'users', ['register_time'], unique=False)
    op.create_table('pushnews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=64), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('to_confirmed', sa.String(length=100), nullable=True),
    sa.Column('to_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushnews_create_time'), 'pushnews', ['create_time'], unique=False)
    op.create_table('pushtexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('to_confirmed', sa.String(length=100), nullable=True),
    sa.Column('to_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushtexts_create_time'), 'pushtexts', ['create_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pushtexts_create_time'), table_name='pushtexts')
    op.drop_table('pushtexts')
    op.drop_index(op.f('ix_pushnews_create_time'), table_name='pushnews')
    op.drop_table('pushnews')
    op.drop_index(op.f('ix_users_register_time'), table_name='users')
    op.drop_table('users')
    op.drop_table('registrations')
    op.drop_table('wechatusers')
    op.drop_table('roles')
    op.drop_table('groups')
    op.drop_table('auth')
    ### end Alembic commands ###
