"""to_confirmed_id

Revision ID: cc61610e434c
Revises: 134a7f3cb501
Create Date: 2017-05-16 16:28:03.902085

"""

# revision identifiers, used by Alembic.
revision = 'cc61610e434c'
down_revision = '134a7f3cb501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushtexts', sa.Column('to_confirmed', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pushtexts', 'to_confirmed')
    ### end Alembic commands ###
