"""settings

Revision ID: d02acdbb9254
Revises: None
Create Date: 2017-05-21 09:23:44.142853

"""

# revision identifiers, used by Alembic.
revision = 'd02acdbb9254'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechatusers', sa.Column('user_setting', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechatusers', 'user_setting')
    ### end Alembic commands ###
