"""add posttext

Revision ID: fdfd1ddd8b20
Revises: 51d46cd72fc7
Create Date: 2017-05-16 09:34:22.571863

"""

# revision identifiers, used by Alembic.
revision = 'fdfd1ddd8b20'
down_revision = '51d46cd72fc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushtexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=True),
    sa.Column('textarea', sa.Text(), nullable=True),
    sa.Column('is_to_all', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('to_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['to_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushtexts_create_time'), 'pushtexts', ['create_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pushtexts_create_time'), table_name='pushtexts')
    op.drop_table('pushtexts')
    ### end Alembic commands ###
